### ISSUE TITLE
Change API token name

### ISSUE THREAD

**Issue by csgillespie** [JohnMcIntyreJR/recipes#4]
https://github.com/JohnMcIntyreJR/getrecipes/blob/master/R/get_api.R#L14

Update the docs in get_api

**Comment by JohnMcIntyreJR** [comment]
@csgillespie Ah yeah forgot to change that! Presume I can also get rid of https://github.com/JohnMcIntyreJR/getrecipes/blob/e30f1bd312a50b6de199960dc668e59cfa1f851c/R/get_api.R#L18 as this is just in relation to version 1 of typeform API

**Comment by csgillespie** [comment]
What do you think?

**Comment by JohnMcIntyreJR** [comment]
Haha yes, me thinking out loud again!
